# Generated by Django 2.2.8 on 2020-03-13 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Twilio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phoneverification',
            name='created_date',
        ),
    ]
