# Generated by Django 2.2.8 on 2020-01-13 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200110_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='verification_code',
        ),
    ]
