# Generated by Django 2.2.8 on 2020-03-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200110_1221'),
        ('users', '0011_auto_20200102_0253'),
    ]

    operations = [
    ]
