version: '3.3'

services:
    web:
        env_file:
            - .env
        build: .
        command: python /code/manage.py runserver 0.0.0.0:8001
        volumes:
            - .:/code
        ports:
            - 8001:8001
        depends_on:
            - db
    db:
        image: postgres:11
        volumes:
            - postgres_data:/var/lib/postgresql/data/

volumes:
    postgres_data:
