version: '3.7'

services:
    web:
        env_file:
            - uat.env
        build: .
        # command: python /code/manage.py runserver 0.0.0.0:8000
        command: python /code/manage.py collectstatic --noinput
        command: gunicorn blog_project.wsgi -b 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - 8000:8000
        depends_on:
            - db
    db:
        image: postgres:11
        volumes:
            - postgres_data:/var/lib/postgresql/data/

volumes:
    postgres_data:
