# Generated by Django 2.2.4 on 2020-01-06 13:14

import New_Users.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_enumfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='New_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Job_title', models.CharField(max_length=30)),
                ('Employer', models.CharField(max_length=30)),
                ('Income', models.IntegerField()),
                ('Employment_type', django_enumfield.db.fields.EnumField(default=1, enum=New_Users.models.EmploymentStyle)),
                ('Education', django_enumfield.db.fields.EnumField(default=0, enum=New_Users.models.EducationStyle)),
                ('ZipCode', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Household_name', models.CharField(max_length=100)),
                ('Household_income', models.IntegerField()),
                ('FriendType', django_enumfield.db.fields.EnumField(default=0, enum=New_Users.models.FriendTypeStyle)),
                ('FriendPermission', models.BooleanField(default=False)),
                ('FriendEmail', models.EmailField(max_length=254)),
                ('User_email_created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
